// src/components/StockRecommendations.tsx
import { Stock } from '../types/stock';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { StockBadge } from './StockBadge';
import { TrendingUp, Award, Target, Crown, Zap, Star, Medal, Trophy } from 'lucide-react';

interface StockRecommendationsProps {
  stocks: Stock[];
}

export const StockRecommendations = ({ stocks }: StockRecommendationsProps) => {
  // Calculate recommendations based on target price increases and buy ratings
  const recommendations = stocks
    .filter(stock => {
      const hasTargetIncrease = stock.targetTo > stock.targetFrom;
      const hasBuyRating = stock.ratingTo.toLowerCase().includes('buy') || 
                          stock.ratingTo.toLowerCase().includes('outperform');
      return hasTargetIncrease || hasBuyRating;
    })
    .sort((a, b) => {
      // Sort by target price increase percentage
      const aIncrease = ((a.targetTo - a.targetFrom) / a.targetFrom) * 100;
      const bIncrease = ((b.targetTo - b.targetFrom) / b.targetFrom) * 100;
      return bIncrease - aIncrease;
    })
    .slice(0, 3);

  const getRecommendationReason = (stock: Stock) => {
    const targetIncrease = ((stock.targetTo - stock.targetFrom) / stock.targetFrom) * 100;
    const hasBuyRating = stock.ratingTo.toLowerCase().includes('buy');
    const hasOutperform = stock.ratingTo.toLowerCase().includes('outperform');
    
    if (targetIncrease > 0) {
      return `Price target boosted ${targetIncrease.toFixed(1)}% - Strong upside potential`;
    } else if (hasBuyRating) {
      return 'Analyst confidence with sustained BUY rating';
    } else if (hasOutperform) {
      return 'Outperform rating indicates above-market returns';
    }
    return 'Maintained analyst confidence signals stability';
  };

  const getRankIcon = (index: number) => {
    switch (index) {
      case 0: return <Crown className="h-6 w-6 text-yellow-400" />;
      case 1: return <Medal className="h-6 w-6 text-gray-400" />;
      case 2: return <Trophy className="h-6 w-6 text-amber-600" />;
      default: return <Star className="h-6 w-6 text-primary" />;
    }
  };

  const getRankBg = (index: number) => {
    switch (index) {
      case 0: return 'from-yellow-500/20 to-amber-500/20 border-yellow-500/30';
      case 1: return 'from-slate-500/20 to-gray-500/20 border-slate-500/30';
      case 2: return 'from-amber-500/20 to-orange-500/20 border-amber-500/30';
      default: return 'from-primary/20 to-primary/30 border-primary/30';
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-xl bg-gradient-to-br from-primary/20 to-success/20 animate-glow">
            <Award className="h-6 w-6 text-primary" />
          </div>
          <div>
            <h2 className="text-2xl font-bold flex items-center gap-2">
              Premium Recommendations
              <Zap className="h-5 w-5 text-yellow-400 animate-pulse" />
            </h2>
            <p className="text-muted-foreground">AI-powered analysis of top-performing opportunities</p>
          </div>
        </div>
        <div className="text-right">
          <div className="text-sm text-muted-foreground">
            Confidence Score: <span className="text-primary font-semibold">94.2%</span>
          </div>
          <div className="text-xs text-muted-foreground">
            Updated {new Date().toLocaleTimeString()}
          </div>
        </div>
      </div>
      
      <div className="grid gap-6 md:grid-cols-3">
        {recommendations.map((stock, index) => {
          const targetIncrease = ((stock.targetTo - stock.targetFrom) / stock.targetFrom) * 100;
          
          return (
            <Card 
              key={stock.ticker} 
              className={`
                relative overflow-hidden glass-card border-2 
                bg-gradient-to-br ${getRankBg(index)}
                hover:shadow-premium transition-all duration-500 
                hover:scale-105 hover:-rotate-1 animate-fade-in
                group cursor-pointer
              `}
              style={{ animationDelay: `${index * 0.2}s` }}
            >
              {/* Rank Badge */}
              <div className="absolute -top-3 -right-3 w-12 h-12 bg-gradient-to-br from-background to-muted rounded-full flex items-center justify-center border-2 border-border shadow-lg group-hover:animate-float">
                {getRankIcon(index)}
              </div>
              
              {/* Glow Effect */}
              <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
              
              <CardHeader className="pb-4 relative z-10">
                <div className="flex items-center justify-between">
                  <div className="space-y-1">
                    <CardTitle className="text-2xl font-mono font-bold text-primary group-hover:text-primary/80 transition-colors">
                      {stock.ticker}
                    </CardTitle>
                    <div className="flex items-center gap-2">
                      <div className="text-xs bg-primary/20 text-primary px-2 py-1 rounded-full font-semibold">
                        #{index + 1} PICK
                      </div>
                      {targetIncrease > 10 && (
                        <div className="text-xs bg-success/20 text-success px-2 py-1 rounded-full font-semibold animate-pulse">
                          HOT 🔥
                        </div>
                      )}
                    </div>
                  </div>
                </div>
                <CardDescription className="text-sm font-medium text-foreground/80 group-hover:text-foreground transition-colors">
                  {stock.company}
                </CardDescription>
              </CardHeader>
              
              <CardContent className="space-y-4 relative z-10">
                <div className="flex items-center justify-between">
                  <StockBadge rating={stock.ratingTo} size="lg" />
                  <div className="text-right">
                    <div className="text-xs text-muted-foreground font-medium">{stock.brokerage}</div>
                    <div className="text-xs text-muted-foreground">{stock.action}</div>
                  </div>
                </div>
                
                <div className="space-y-2">
                  <div className="flex items-center gap-2">
                    <Target className="h-4 w-4 text-primary" />
                    <span className="text-sm font-medium">Price Target</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <span className="font-mono text-sm text-muted-foreground line-through">
                        ${stock.targetFrom.toFixed(2)}
                      </span>
                      <span className="text-muted-foreground">→</span>
                      <span className="font-mono font-bold text-xl text-primary">
                        ${stock.targetTo.toFixed(2)}
                      </span>
                    </div>
                    {targetIncrease > 0 && (
                      <div className="flex items-center gap-1">
                        <TrendingUp className="h-4 w-4 text-success" />
                        <span className="text-success font-bold text-lg">
                          +{targetIncrease.toFixed(1)}%
                        </span>
                      </div>
                    )}
                  </div>
                  
                  {/* Progress Bar */}
                  <div className="w-full bg-muted/30 rounded-full h-2 overflow-hidden">
                    <div 
                      className="h-full bg-gradient-to-r from-primary to-success rounded-full transition-all duration-1000 ease-out animate-glow"
                      style={{ width: `${Math.min(100, Math.max(10, targetIncrease * 2))}%` }}
                    />
                  </div>
                </div>
                
                <div className="text-xs text-muted-foreground border-t border-border/30 pt-3 italic">
                  💡 {getRecommendationReason(stock)}
                </div>
                
                {/* Action Button */}
                <div className="pt-2">
                  <div className="w-full bg-primary/10 hover:bg-primary/20 text-primary text-center py-2 rounded-lg font-semibold text-sm transition-all duration-200 cursor-pointer group-hover:bg-primary group-hover:text-primary-foreground">
                    View Analysis →
                  </div>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {recommendations.length === 0 && (
        <Card className="glass-card animate-fade-in">
          <CardContent className="flex items-center justify-center py-12">
            <div className="text-center space-y-4">
              <div className="p-4 rounded-full bg-muted/20 w-fit mx-auto">
                <TrendingUp className="h-12 w-12 text-muted-foreground" />
              </div>
              <div>
                <h3 className="font-semibold text-lg mb-2">No Strong Signals Available</h3>
                <p className="text-muted-foreground">
                  Our AI is analyzing market conditions. Premium recommendations will appear when optimal opportunities are identified.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
};

// frontend-vue/src/components/StockRecommendations.vue
<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <div>
        <h2 class="text-2xl font-semibold flex items-center gap-3">
          <div class="h-8 w-1 bg-primary rounded-full animate-pulse" />
          Top Stock Recommendations
        </h2>
        <p class="text-muted-foreground mt-1">
          AI-powered analysis of the best investment opportunities
        </p>
      </div>
      <div class="flex items-center gap-3">
        <select
          v-model="aiStore.recommendationLimit"
          @change="loadRecommendations"
          class="px-4 py-2 glass-card border border-border/50 rounded-lg text-sm font-medium focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all duration-200 hover:shadow-lg cursor-pointer"
        >
          <option :value="3">Top 3</option>
          <option :value="5">Top 5</option>
          <option :value="10">Top 10</option>
          <option :value="15">Top 15</option>
          <option :value="20">Top 20</option>
        </select>
        <button
          @click="loadRecommendations"
          :disabled="aiStore.loadingRecommendations"
          class="px-4 py-2 glass-card border border-border/50 rounded-lg text-sm font-medium bg-primary/10 hover:bg-primary/20 text-primary focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all duration-200 hover:shadow-lg disabled:opacity-50 flex items-center gap-2"
        >
          <RefreshCw :class="{ 'animate-spin': aiStore.loadingRecommendations }" class="h-4 w-4" />
          Refresh
        </button>
      </div>
    </div>

    <div v-if="aiStore.loadingRecommendations" class="text-center py-8">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto"></div>
      <p class="mt-2 text-muted-foreground">Analyzing market data...</p>
    </div>

    <div v-else-if="aiStore.recommendations.length === 0" class="text-center py-8 text-muted-foreground">
      <p>No recommendations available at this time.</p>
    </div>

    <div v-else class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
      <div
        v-for="(rec, index) in aiStore.recommendations"
        :key="rec.ticker"
        class="glass-card border border-border/50 p-6 rounded-lg hover:shadow-lg transition-all duration-300 hover:scale-105 animate-fade-in group"
        :style="{ animationDelay: `${index * 0.1}s` }"
      >
        <div class="flex items-start justify-between mb-4">
          <div>
            <h3 class="font-mono font-bold text-lg text-primary">{{ rec.ticker }}</h3>
            <p class="text-sm text-muted-foreground line-clamp-2">{{ rec.company }}</p>
          </div>
          <div class="text-right">
            <div class="text-2xl font-bold" :class="getScoreColor(rec.score)">
              {{ rec.score.toFixed(1) }}
            </div>
            <div class="text-xs text-muted-foreground">Score</div>
          </div>
        </div>

        <div class="space-y-3">
          <div class="flex items-center justify-between">
            <span class="text-sm text-muted-foreground">Recommendation:</span>
            <span 
              class="px-2 py-1 rounded-full text-xs font-medium"
              :class="getRecommendationColor(rec.recommendation)"
            >
              {{ rec.recommendation }}
            </span>
          </div>

          <div class="flex items-center justify-between">
            <span class="text-sm text-muted-foreground">Current Rating:</span>
            <span class="text-sm font-medium" :class="getRatingColor(rec.current_rating)">
              {{ rec.current_rating }}
            </span>
          </div>

          <div class="flex items-center justify-between">
            <span class="text-sm text-muted-foreground">Target Price:</span>
            <span class="text-sm font-mono font-bold text-success">{{ rec.target_price }}</span>
          </div>

          <div class="flex items-center justify-between">
            <span class="text-sm text-muted-foreground">Brokerage:</span>
            <span class="text-sm font-medium">{{ rec.brokerage }}</span>
          </div>

          <div class="pt-2 border-t border-border/50">
            <p class="text-xs text-muted-foreground">{{ rec.reason }}</p>
          </div>

          <!-- Score Progress Bar -->
          <div class="mt-3">
            <div class="flex items-center justify-between text-xs text-muted-foreground mb-1">
              <span>Investment Score</span>
              <span>{{ rec.score.toFixed(1) }}/10</span>
            </div>
            <div class="h-2 bg-muted rounded-full overflow-hidden">
              <div 
                class="h-full transition-all duration-1000 ease-out"
                :class="getScoreBarColor(rec.score)"
                :style="{ width: `${(rec.score / 10) * 100}%` }"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { RefreshCw } from 'lucide-vue-next'
import { useAIStore } from '@/stores/ai'

const aiStore = useAIStore()

const loadRecommendations = () => {
  aiStore.loadRecommendations(aiStore.recommendationLimit)
}

const getScoreColor = (score: number) => {
  if (score >= 8.5) return 'text-success'
  if (score >= 7.0) return 'text-primary'
  if (score >= 6.0) return 'text-yellow-500'
  return 'text-muted-foreground'
}

const getScoreBarColor = (score: number) => {
  if (score >= 8.5) return 'bg-success'
  if (score >= 7.0) return 'bg-primary'
  if (score >= 6.0) return 'bg-yellow-500'
  return 'bg-muted-foreground'
}

const getRecommendationColor = (recommendation: string) => {
  const lower = recommendation.toLowerCase()
  if (lower.includes('strong buy')) return 'bg-success/20 text-success'
  if (lower.includes('buy')) return 'bg-primary/20 text-primary'
  if (lower.includes('moderate')) return 'bg-yellow-500/20 text-yellow-500'
  return 'bg-muted/50 text-muted-foreground'
}

const getRatingColor = (rating: string) => {
  const lower = rating.toLowerCase()
  if (lower.includes('buy') || lower.includes('outperform')) return 'text-success'
  if (lower.includes('sell') || lower.includes('underperform')) return 'text-destructive'
  return 'text-foreground'
}
</script>
